services:
  db:
    image: postgres:16
    container_name: sc3020_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sc3020_project1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./csv:/csv:ro

volumes:
  pgdata: